const products=[
{id:1,name:"Organic Mansoori Rice",cat:"Organic Food",price:50,unit:"1 kg",icon:"🍚"},{id:2,name:"Fresh Organic Vegetables",cat:"Organic Vegetables",price:80,unit:"1 kg",icon:"🥬"},{id:3,name:"Natural Humic",cat:"Farm Inputs",price:299,unit:"1 litre",icon:"🧴"},{id:4,name:"Cow Dung Ash",cat:"Farm Inputs",price:149,unit:"1 kg",icon:"🌱"},{id:5,name:"FFJ Fermented Fruit Juice",cat:"Farm Inputs",price:199,unit:"1 litre",icon:"🍎"},{id:6,name:"Fresh Potato",cat:"Organic Vegetables",price:40,unit:"1 kg",icon:"🥔"},{id:7,name:"Organic Cauliflower",cat:"Organic Vegetables",price:60,unit:"1 kg",icon:"🥦"},{id:8,name:"Trichoderma Bio Input",cat:"Farm Inputs",price:249,unit:"500 g",icon:"🧫"}];
let cart=JSON.parse(localStorage.getItem("ff_cart")||"[]"),orders=JSON.parse(localStorage.getItem("ff_orders")||"[]");
function money(n){return "₹"+n} function renderProducts(target="products"){const cat=document.getElementById("category")?.value||"all",q=(document.getElementById("searchInput")?.value||"").toLowerCase();const list=products.filter(p=>(cat==="all"||p.cat===cat)&&(!q||p.name.toLowerCase().includes(q)||p.cat.toLowerCase().includes(q)));document.getElementById(target).innerHTML=list.map(p=>`<div class="card"><div class="pic">${p.icon}</div><div class="cardBody"><span class="tag">${p.cat}</span><h3>${p.name}</h3><div class="price">${money(p.price)} <small>/ ${p.unit}</small></div><button class="add" onclick="addCart(${p.id})">🛒 Cart में डालें</button></div></div>`).join("")||"<p>कोई product नहीं मिला।"}
function renderHome(){renderProducts("homeProducts")} function addCart(id){cart.push(id);localStorage.setItem("ff_cart",JSON.stringify(cart));updateCart();toast("Product cart में जोड़ दिया गया")} function updateCart(){document.getElementById("cartCount").textContent=cart.length}
function showPage(id,btn){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));document.getElementById(id).classList.remove("hidden");document.querySelectorAll(".nav button").forEach(x=>x.classList.remove("active"));if(btn)btn.classList.add("active");if(id==="shop")renderProducts();if(id==="home")renderHome();if(id==="orders")renderOrders();scrollTo({top:0,behavior:"smooth"})} function searchAll(){showPage("shop");renderProducts()}
function showCart(){const rows=cart.map((id,i)=>{const p=products.find(x=>x.id===id);return `<div class="order"><b>${p.icon} ${p.name}</b><br>${money(p.price)} / ${p.unit} <button onclick="removeCart(${i})">✕</button></div>`}).join("");const total=cart.reduce((s,id)=>s+products.find(p=>p.id===id).price,0);openModal(`<h2>🛒 आपका Cart</h2>${rows||"<p>Cart खाली है।</p>"}<hr><h3>Total: ${money(total)}</h3>${cart.length?'<button class="primary" onclick="checkout()">Checkout</button>':""}`)}
function removeCart(i){cart.splice(i,1);localStorage.setItem("ff_cart",JSON.stringify(cart));updateCart();showCart()}
function checkout(){openModal(`<h2>📦 Checkout</h2><label>नाम</label><input id="cname"><label>मोबाइल</label><input id="cphone"><label>पूरा पता</label><textarea id="caddress" rows="3"></textarea><label>Payment</label><select id="pay"><option>COD</option><option>UPI</option></select><button class="primary" onclick="placeOrder()">Order Place करें</button>`)}
async function placeOrder(){const name=document.getElementById("cname").value.trim(),phone=document.getElementById("cphone").value.trim(),address=document.getElementById("caddress").value.trim(),payment=document.getElementById("pay").value;if(!name||!phone||!address){toast("कृपया सभी details भरें");return}const total=cart.reduce((s,id)=>s+products.find(p=>p.id===id).price,0);const order={name,phone,address,total,payment};if(typeof saveOrderToBackend==="function"&&ffSupabase){const r=await saveOrderToBackend(order);if(r.error){toast(r.error.message);return}order.id=r.data.id;order.status=r.data.status||"pending";}else{order.id="FF"+Date.now().toString().slice(-6);order.status="Pending";}orders.unshift(order);localStorage.setItem("ff_orders",JSON.stringify(orders));cart=[];localStorage.setItem("ff_cart","[]");updateCart();closeModal();showPage("orders");renderOrders();toast("Order successfully place हो गया")}
function renderOrders(){document.getElementById("ordersList").innerHTML=orders.length?orders.map(o=>`<div class="order"><b>Order #${o.id}</b><br>Total: ${money(o.total)}<br>Customer: ${o.name}<br>Status: <strong>${o.status}</strong></div>`).join(""):"<p>अभी कोई order नहीं है।</p>"}
function openAuth(){openModal(`<h2>👤 Login / Sign Up</h2><input id="authEmail" placeholder="Email"><input id="authPass" type="password" placeholder="Password"><input id="authName" placeholder="नाम (Sign Up)"/><button class="primary" onclick="doAuth()">Continue</button>`)}
async function doAuth(){const e=document.getElementById("authEmail").value,p=document.getElementById("authPass").value,n=document.getElementById("authName").value;if(!ffSupabase){toast("Supabase configure करें");return}const r=n?await backendSignUp(e,p,n):await backendSignIn(e,p);if(r.error){toast(r.error.message);return}closeModal();toast("Login successful")}
function openModal(html){document.getElementById("modalContent").innerHTML=html;document.getElementById("modal").classList.remove("hidden")} function closeModal(){document.getElementById("modal").classList.add("hidden")} function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.style.display="block";setTimeout(()=>t.style.display="none",2200)} renderHome();renderProducts();updateCart();
